[project]
name = "snoopervisor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "croniter>=6.0.0",
    "dynaconf>=3.2.12",
    "psutil>=7.1.3",
    "pycron>=3.2.0",
    "schedule>=1.2.2",
]
