[users]
ignore = [
    "root",
    "systemd-resolve",
    "systemd-oom",
    "systemd-timesync",
]

[watchers.cpu]
enabled = true
threshold = 100
schedule = "*/5 * * * *"

[watchers.memory]
enabled = true
threshold = 200000000
schedule = "* * * * *"